// ssbu/matchups/character-data.js

// All values are one of: "low", "mid", "high", "top"
// Attributes:
// - speed      (how fast they move/act)
// - range      (disjoints, weapon length)
// - weight     (survivability)
// - killpower  (how early they can kill)
// - combo      (combo/extention strength)
// - mobility   (overall movement / air drift)
// - zoning     (projectiles & long-range control)
// - recovery   (quality & mixups of recovery)
// - ledgetrap  (how scary they are at ledge)
// - offstage   (edgeguard ability)

const SSBU_CHAR_DATA = {
  "Banjo & Kazooie": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Bayonetta": {
    speed: "mid",
    range: "mid",
    weight: "low",
    killpower: "mid",
    combo: "top",
    mobility: "high",
    zoning: "low",
    recovery: "high",
    ledgetrap: "high",
    offstage: "high"
  },
  "Bowser": {
    speed: "mid",
    range: "high",
    weight: "top",
    killpower: "top",
    combo: "mid",
    mobility: "mid",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Bowser Jr.": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Byleth": {
    speed: "low",
    range: "top",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "low",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Captain Falcon": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "top",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Chrom": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "high",
    zoning: "low",
    recovery: "low",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Cloud": {
    speed: "mid",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "low",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Corrin": {
    speed: "mid",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Daisy": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "top",
    mobility: "high",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Dark Pit": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Dark Samus": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Diddy Kong": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "high",
    mobility: "high",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "top",
    offstage: "high"
  },
  "Donkey Kong": {
    speed: "mid",
    range: "high",
    weight: "high",
    killpower: "top",
    combo: "mid",
    mobility: "mid",
    zoning: "low",
    recovery: "low",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Dr. Mario": {
    speed: "low",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "low",
    zoning: "mid",
    recovery: "low",
    ledgetrap: "mid",
    offstage: "low"
  },
  "Duck Hunt": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "top",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Falco": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "high",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Fox": {
    speed: "top",
    range: "low",
    weight: "low",
    killpower: "mid",
    combo: "high",
    mobility: "top",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Ganondorf": {
    speed: "low",
    range: "mid",
    weight: "high",
    killpower: "top",
    combo: "low",
    mobility: "low",
    zoning: "low",
    recovery: "low",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Greninja": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "top",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Hero": {
    speed: "mid",
    range: "high",
    weight: "mid",
    killpower: "top",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Ice Climbers": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "top",
    mobility: "mid",
    zoning: "mid",
    recovery: "low",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Ike": {
    speed: "low",
    range: "high",
    weight: "mid",
    killpower: "top",
    combo: "mid",
    mobility: "low",
    zoning: "low",
    recovery: "low",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Incineroar": {
    speed: "low",
    range: "mid",
    weight: "high",
    killpower: "top",
    combo: "mid",
    mobility: "low",
    zoning: "low",
    recovery: "low",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Inkling": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "high",
    mobility: "high",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "high",
    offstage: "high"
  },
  "Isabelle": {
    speed: "low",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "low",
    mobility: "low",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Jigglypuff": {
    speed: "mid",
    range: "low",
    weight: "low",
    killpower: "high",
    combo: "high",
    mobility: "top",
    zoning: "low",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "top"
  },
  "Joker": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "top",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "high",
    offstage: "high"
  },
  "Kazuya": {
    speed: "low",
    range: "low",
    weight: "high",
    killpower: "top",
    combo: "top",
    mobility: "low",
    zoning: "low",
    recovery: "low",
    ledgetrap: "mid",
    offstage: "low"
  },
  "Ken": {
    speed: "mid",
    range: "low",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "King Dedede": {
    speed: "low",
    range: "high",
    weight: "top",
    killpower: "high",
    combo: "low",
    mobility: "low",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "King K. Rool": {
    speed: "mid",
    range: "high",
    weight: "top",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Kirby": {
    speed: "low",
    range: "low",
    weight: "low",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Link": {
    speed: "mid",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Little Mac": {
    speed: "high",
    range: "low",
    weight: "mid",
    killpower: "top",
    combo: "low",
    mobility: "high",
    zoning: "low",
    recovery: "low",
    ledgetrap: "mid",
    offstage: "low"
  },
  "Lucario": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Lucas": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Lucina": {
    speed: "high",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "high",
    zoning: "low",
    recovery: "high",
    ledgetrap: "high",
    offstage: "high"
  },
  "Luigi": {
    speed: "low",
    range: "low",
    weight: "mid",
    killpower: "high",
    combo: "top",
    mobility: "low",
    zoning: "low",
    recovery: "low",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Mario": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "high",
    mobility: "mid",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Marth": {
    speed: "high",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "high",
    zoning: "low",
    recovery: "high",
    ledgetrap: "high",
    offstage: "high"
  },
  "Mega Man": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "top",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Meta Knight": {
    speed: "high",
    range: "low",
    weight: "low",
    killpower: "mid",
    combo: "high",
    mobility: "top",
    zoning: "low",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Mewtwo": {
    speed: "mid",
    range: "high",
    weight: "low",
    killpower: "high",
    combo: "mid",
    mobility: "high",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Mii Brawler": {
    speed: "high",
    range: "low",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "high",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Mii Gunner": {
    speed: "low",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "low",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Mii Swordfighter": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Min Min": {
    speed: "mid",
    range: "top",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "low",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Mr. Game & Watch": {
    speed: "high",
    range: "low",
    weight: "low",
    killpower: "high",
    combo: "high",
    mobility: "high",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "high",
    offstage: "high"
  },
  "Ness": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Olimar": {
    speed: "mid",
    range: "high",
    weight: "low",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "low"
  },
  "Pac-Man": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "high",
    mobility: "mid",
    zoning: "high",
    recovery: "high",
    ledgetrap: "top",
    offstage: "mid"
  },
  "Palutena": {
    speed: "high",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "high",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Peach": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "top",
    mobility: "high",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Pichu": {
    speed: "high",
    range: "low",
    weight: "low",
    killpower: "high",
    combo: "top",
    mobility: "high",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Pikachu": {
    speed: "high",
    range: "mid",
    weight: "low",
    killpower: "high",
    combo: "top",
    mobility: "top",
    zoning: "high",
    recovery: "top",
    ledgetrap: "top",
    offstage: "top"
  },
  "Piranha Plant": {
    speed: "low",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "low",
    mobility: "low",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Pit": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Pokémon Trainer": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "high",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "high",
    offstage: "high"
  },
  "Pyra/Mythra": {
    speed: "high",      // Mythra
    range: "high",
    weight: "mid",
    killpower: "top",   // Pyra
    combo: "high",
    mobility: "high",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "R.O.B.": {
    speed: "mid",
    range: "high",
    weight: "high",
    killpower: "high",
    combo: "high",
    mobility: "mid",
    zoning: "high",
    recovery: "top",
    ledgetrap: "top",
    offstage: "high"
  },
  "Richter": {
    speed: "low",
    range: "top",
    weight: "mid",
    killpower: "high",
    combo: "low",
    mobility: "low",
    zoning: "top",
    recovery: "low",
    ledgetrap: "high",
    offstage: "low"
  },
  "Ridley": {
    speed: "mid",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Robin": {
    speed: "low",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "low",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Rosalina & Luma": {
    speed: "mid",
    range: "high",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Roy": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "top",
    combo: "high",
    mobility: "high",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Ryu": {
    speed: "mid",
    range: "low",
    weight: "mid",
    killpower: "high",
    combo: "high",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Samus": {
    speed: "low",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "low",
    zoning: "top",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Sephiroth": {
    speed: "mid",
    range: "top",
    weight: "low",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "high"
  },
  "Sheik": {
    speed: "top",
    range: "low",
    weight: "low",
    killpower: "low",
    combo: "top",
    mobility: "top",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Shulk": {
    speed: "mid",
    range: "top",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "high",
    zoning: "low",
    recovery: "high",
    ledgetrap: "high",
    offstage: "high"
  },
  "Simon": {
    speed: "low",
    range: "top",
    weight: "mid",
    killpower: "high",
    combo: "low",
    mobility: "low",
    zoning: "top",
    recovery: "low",
    ledgetrap: "high",
    offstage: "low"
  },
  "Snake": {
    speed: "mid",
    range: "mid",
    weight: "high",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "top",
    recovery: "mid",
    ledgetrap: "top",
    offstage: "mid"
  },
  "Sonic": {
    speed: "top",
    range: "low",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "top",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Sora": {
    speed: "mid",
    range: "mid",
    weight: "low",
    killpower: "mid",
    combo: "high",
    mobility: "high",
    zoning: "mid",
    recovery: "top",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Steve": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "top",
    combo: "top",
    mobility: "mid",
    zoning: "high",
    recovery: "high",
    ledgetrap: "top",
    offstage: "high"
  },
  "Terry": {
    speed: "mid",
    range: "low",
    weight: "mid",
    killpower: "top",
    combo: "high",
    mobility: "mid",
    zoning: "mid",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Toon Link": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Villager": {
    speed: "low",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "low",
    mobility: "low",
    zoning: "high",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "mid"
  },
  "Wario": {
    speed: "mid",
    range: "low",
    weight: "mid",
    killpower: "top",
    combo: "top",
    mobility: "top",
    zoning: "low",
    recovery: "mid",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Wii Fit Trainer": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "mid",
    mobility: "mid",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Wolf": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "top",
    combo: "high",
    mobility: "high",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Yoshi": {
    speed: "mid",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "high",
    mobility: "high",
    zoning: "mid",
    recovery: "high",
    ledgetrap: "mid",
    offstage: "high"
  },
  "Young Link": {
    speed: "high",
    range: "mid",
    weight: "mid",
    killpower: "mid",
    combo: "high",
    mobility: "high",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Zelda": {
    speed: "low",
    range: "mid",
    weight: "mid",
    killpower: "high",
    combo: "low",
    mobility: "low",
    zoning: "high",
    recovery: "mid",
    ledgetrap: "high",
    offstage: "mid"
  },
  "Zero Suit Samus": {
    speed: "top",
    range: "mid",
    weight: "low",
    killpower: "high",
    combo: "high",
    mobility: "top",
    zoning: "mid",
    recovery: "top",
    ledgetrap: "high",
    offstage: "top"
  }
};
